# Generated by Django 5.1.4 on 2024-12-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deafultsHH',
            field=models.CharField(default='koko', max_length=100),
            preserve_default=False,
        ),
    ]
