# Generated by Django 5.1.4 on 2024-12-17 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_deafultshh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deafultsHH',
        ),
    ]
